source 'https://rubygems.org'
gem "jekyll", :git => "https://github.com/jekyll/jekyll.git"
gem 'jekyll-tagging'
gem 'ruby-nuggets'
gem 'hen'
gem 'rake'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jemoji'
gem 'kramdown'
gem 'liquid'
gem 'maruku'
gem 'mercenary'
gem 'pygments.rb'
gem 'rdiscount'
gem 'RedCloth'
gem "ffi", ">= 1.9.24"
gem "nokogiri", ">= 1.8.5"
